name: Documentation Sync

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docs-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Validate API Documentation
        run: npm run docs:validate:api
        
      - name: Validate Documentation Examples
        run: npm run docs:validate:examples
        
      - name: Validate Bundle Size Documentation
        run: npm run docs:validate:metrics
        
      - name: Validate Internal Links
        run: npm run docs:validate:links
        
      - name: Generate Link Report
        run: npm run docs:report:links
        
      - name: Run Tests
        run: npm run test
        
      - name: Run Storybook Tests
        run: npm run test:stories
        
      - name: Check for Documentation Drift
        run: |
          git diff --exit-code docs/ || {
            echo "Documentation changes detected but not committed"
            echo "Please run 'npm run docs:generate' and commit the changes"
            exit 1
          }
          
      - name: Build Project
        run: npm run build
        
      - name: Upload Documentation Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: documentation-report
          path: docs/generated/
          
  auto-update-docs:
    runs-on: ubuntu-latest
    needs: docs-validation
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update Bundle Metrics
        run: npm run docs:update:metrics
        
      - name: Generate API Documentation
        run: npm run docs:generate
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit documentation updates
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "docs: Auto-update documentation [skip ci]" || exit 0
          git push
